### ISSUE TITLE
Question - How to modify zAppBuild on our installation while benefiting from the developments made by the IBM team?

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/dbb-zappbuild#248]
Hi,

zAppbuild is a component that seems essential to us to use IBM Dependency Based Build: it provides a very large number of basic services that would be difficult to write ourselves, and it offers many use cases as initial models.

However zAppbuild is not an IBM Dependency Based Build component and it must be adapted to the context of the user site because it is rare that it can be used directly from its recovery.

My question is: how to benefit from the developments of zAppbuild if we modify certain elements ourselves?

Shouldn't rules be implemented to allow changes and postponements of zAppbuild -specific developments in our modified version, not necessarily compatible?

Shouldn't it identify elements "not to be modified", and elements "authorized in modification"?
Can be cut certain current elements to dissociate the "heart" parts not to be modified, and the "peripheral" parts authorized in modification?

Thanks.

**Comment by dennis-behm** [comment]
Hi @FALLAI-Denis,

sorry for the delay in answering your questions/requests. I was on a longer family leave, back now. A bit unfortunate that nobody else has responded to it, while I was away. Customers seem to be very cautious about collaborating / sharing their views through GitHub - still on a learning curve to share their views/opinion through those platforms. But, I see plenty of requests coming in via email.

We are not intending to lock any specific areas of the zAppBuild sample implementation. It is a community driven project and everyone can propose updates to it through GitHub. Certainly, sharing the idea in advance through an Github Issue makes sense, so that it can be discussed with the community and the maintainers of the project, before preparing a PR to the project.

To answer your questions - it might sound simple, but why not using Git to synchronise the open source project with your customised internal version of it? Certainly, everyone has a slightly modified configured/customised version of zAppBuild running at their shops. If you start with a fork of zAppBuild and retain the history (which means to maintain a remote reference to this project), you can update your fork easily by using git. We have shared some instructions via this paper: [zAppBuild Introduction and Custom Maintenance Strategy](https://www.ibm.com/support/pages/node/6457275). Let me know, if you have any questions on that. And yes, I have seen customers, who have strict rules about the committers in their internal git server, but there are always ways around it.
