### ISSUE TITLE
How To - Debug: BPXWDYN error

### ISSUE THREAD

**Issue by rsjrny** [IBM/dbb-zappbuild#290]
I am receiving the following error when compiling a cobol module

Caused by: com.ibm.dbb.build.BuildException: BGZTK0016E An error occurred running BPXWDYN command 'alloc dd(TMP00004) shr'.

I know this is caused by a blank property value but I cannot tell what one it is because I have no idea where TMP00004 is being assigned.

Are there any suggestions other than adding a bunch of println statements in the groovy files to track it down?

thanks

**Comment by dennis-behm** [comment]
@rsjrny

Rather than implementing checks for blank properties in the build scripts, I think it would be good if the DBB toolkit is validating and checks for blank inputs for the DDStatement API before invoking BPXWDYN.

So, what do you think if the toolkit would throw an DBB exception when the methods of `DDStatement` receive an empty String?

* DDStatement().name()
* DDStatement().dsn()
* DDStatement().options()

Would you mind to open an enhancement request under https://ideas.ibm.com for DBB?

To troubleshoot the situation, my recommendation is to enable the logging of the DBB toolkit, which then will list all the allocations. While the order of allocations might differ, you cannot trust the order in the build script and it is better to troubleshoot with the tracing enabled.

Dennis

**Comment by dennis-behm** [comment]
Please be aware, that DBB 1.x and 2.0 use different logger systems.

DBB 2.0 uses the Simple Logging facility, for details https://www.ibm.com/docs/en/dbb/2.0.0?topic=customization-logging-framework

**Comment by rsjrny** [comment]
I left an enhancement request in ideas. thanks
