### ISSUE TITLE
zAppbuild enhancement - isSQL scanning in Copybooks 

### ISSUE THREAD

**Issue by nlopez1-ibm** [IBM/dbb-zappbuild#47]
Issue:  
When a main program contains no exec-sql stmt but one of its dependencies does, like a copybook, the build fails because the compiler option "SQL" is not provided. 

Solution: 
During the build, if a main program is not "isSQL", spin though its dependencies to determine if any "isSQL".  If so, enable the 'isSQL" compiler option.

**Comment by dajsen** [comment]
Sorry, don't like that solution. If it's implemented then I would like to have a choice, do the spin through or not...

**Comment by nlopez1-ibm** [comment]
Good point.   Setting this in a prop file hard codes it for all programs in the project.   Not ideal.  With spinning across dependencies we can be more selective.

**Comment by dajsen** [comment]
No, it's set on module-level. 
OK, so you have your SQL-code in a lot of copybooks right ? More than 50% of your code, otherwise you will 'pay' for it in every build instead of dealing with it only in the modules involved...

**Comment by nlopez1-ibm** [comment]
Kind of - yes.  Plus I worry about always passing the "SQL" compiler options for non-DB2 programs.   I'm not sure thats a good practice.

**Comment by dennis-behm** [comment]
Probably, I have missed something in the discussion. You can overwrite the `isSQL` property on a file level. If you have a couple of programs, then you can add these files to this list. If you have naming conventions to indicate, you can also use wildcards. Here is an example for `isCICS` from the Mortgage sample:

https://github.com/IBM/dbb-zappbuild/blob/11c17f991e1f2517ad5c5155b00ef939406de794/samples/MortgageApplication/application-conf/file.properties#L22

Within buildUtils.isSQL, this file property 'overwrite' is taken into consideration.
https://github.com/IBM/dbb-zappbuild/blob/11c17f991e1f2517ad5c5155b00ef939406de794/utilities/BuildUtilities.groovy#L264-L270 

I assume, your previous build environment carries these information. Mapping the programs of type 'db2', with an extract of all the pgms in your dbb collection, can give you the delta where you need to set the `isSQL` pgm in file.properties. 

The proposed enhancement is expected to be expensive, because you would need to scan / query all copybooks referenced for the given COBOL file (for a userBuild and pipelineBuild).

**Comment by drbruce-git** [comment]
Just a side comment pointing out that we already scan all copybooks referenced by a  COBOL program so that we can identify and resolve them in the local Git repository to copy them to the copybook data set.  This is done in BuildUtilities.copySourceFiles.  It even creates a list of dependencies (https://github.com/IBM/dbb-zappbuild/blob/development/utilities/BuildUtilities.groovy#L81) that we could return from the method and check to see if any are marked isSQL.
