### ISSUE TITLE
Issue in DBB User Build after enabling cobol_storeSSI

### ISSUE THREAD

**Issue by lauren-li** [IBM/dbb-zappbuild#477]
After enabling ‘cobol_storeSSI=true` in DBB User Build, the build ended up in error:

- `IEW2325E 1224 UNMATCHED QUOTE IN CURRENT CONTROL STATEMENT STREAM.`
  - [Information on IEW2325E](https://www.ibm.com/docs/en/zos/2.1.0?topic=iew2999-iew2325e)
- `IEW2333E 1704 INVALID SYNTAX IN IDENTIFY CONTROL STATEMENT`
  - [Information on IEW2333E](https://www.ibm.com/docs/en/zos/2.1.0?topic=iew2999-iew2333e)

Further analysis found that the `IDENTIFY` statement is exceeding 71 characters in this case.

**Comment by dennis-behm** [comment]
Hi @lauren-li, 

storing the abbreviated hash in a user build scenario is not supported, because the User Build operates outside of of git repository. 

Looking at the implementation, the section about the SSI is not executed on User Builds.

https://github.com/IBM/dbb-zappbuild/blob/dd59b05112791ef1ea5fc710d821cb214b90142d/languages/Cobol.groovy#L301

Would you mind to have another look to your implementation, please?

**Comment by dennis-behm** [comment]
@lauren-li,

I think I am confused. Issue title talks about SSI, but you also talk about the IDENTIFY, which is another path.

However, this is also not executed on User Builds : 

https://github.com/IBM/dbb-zappbuild/blob/dd59b05112791ef1ea5fc710d821cb214b90142d/utilities/BuildUtilities.groovy#L850-L859

**Comment by lauren-li** [comment]
Thanks @dennis-behm for your reply! Upon closer investigation, the issue causing the error is not SSI, but rather the IDENTIFY statement, which you have opened issue #479 for. Thus, I will close this issue (#477) and we can continue addressing the error via issue #479.
