### ISSUE TITLE
Enhance scanOnly scenario

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb-zappbuild#85]
As of today, zAppBuild contains the capability to populate the DBB collections with the dependencies on the source level by using the option `--scanOnly --fullBuild`. In this case the source code is scanned for dependencies, but no outputs are created. In this context, there is a known limitation that the framework does not populate the output collection. However, the scanning process can be performed via LinkEditScanner which is included in the other build types.

We would like to enhance the zAppBuild sample framework to be able to also populate the output collection to support the scenario of migrating to Git/DBB without the need of running an initial full build when using static linkage.

**Comment by dennis-behm** [comment]
Please check the below note for a short sample of this new functionality:
https://github.com/IBM/dbb-zappbuild/pull/87#issuecomment-785893455

**Comment by dennis-behm** [comment]
Feature was delivered via #87 . Closing it.

**Comment by ratnamGT** [comment]
@dennis-behm  Just a question on scanOnly parameter. I have executed scanOnly on my repository and created the results . I have 24 programs in buildlist.txt and build is clean but my BuildReport.html file is blank .It does not show the dependency information in HTML file and also JSON file does not have any program information. Is the BuildReport.html created only in case of FullBuild with load module or in impact build case.
How can I get dependency information in BuildReport.html so that I can view it on web browser

**Comment by dennis-behm** [comment]
> @dennis-behm Just a question on scanOnly parameter. I have executed scanOnly on my repository and created the results . I have 24 programs in buildlist.txt and build is clean but my BuildReport.html file is blank .It does not show the dependency information in HTML file and also JSON file does not have any program information. Is the BuildReport.html created only in case of FullBuild with load module or in impact build case. How can I get dependency information in BuildReport.html so that I can view it on web browser

The `--scanOnly` parameter is only scanning the files and populating the DBB collections with the dependency information. There is no build report created for this build type. You can inspect the `--verbose` log for dependencies or by using the DBB CLI.

Alternatively, you can run a `--fullBuild --preview` . See https://github.com/IBM/dbb-zappbuild/blob/main/docs/BUILD.md#perform-a-build-in-preview-mode

**Comment by ratnamGT** [comment]
Hi @dennis-behm  Thanks for your response , My requirement is , I do not want to create Artifact and loads in the HLQ datasets. I want only scanning the application and generate the Buildreport with dependency information in the HTML file. Is there any other parameter available so that I can achieve this.

**Comment by dennis-behm** [comment]
> Hi @dennis-behm Thanks for your response , My requirement is , I do not want to create Artifact and loads in the HLQ datasets. I want only scanning the application and generate the Buildreport with dependency information in the HTML file. Is there any other parameter available so that I can achieve this.

Please read about the `--fullBuild --preview`. You need to understand that the BuildReport is not a complete list of the dependencies. It documents what DBB has found when resolving the dependencies. For instance it does not contain information about the object-level dependencies that are used in the impact analysis to understand the dependencies pulled in via the linkage editor.
